#!/usr/bin/env python
# coding: utf-8

import os
import shutil
import random

def get_POSCAR(lines, poscar, name, length, atomlist, keyword):
    write_poscar = open(poscar, 'w')
    write_poscar.write("POSCAR_" + name + '\n')
    write_poscar.write('1.0' + '\n')
    write_poscar.write(length + ' ' + '0.0' + ' ' + '0.0' + '\n')
    write_poscar.write('0.0' + ' ' + length + ' ' + '0.0' + '\n')
    write_poscar.write('0.0' + ' ' + '0.0' + ' ' + length + '\n')
    
    for j in range(len(atomlist)):
        write_poscar.write(atomlist[j] + ' ')
    write_poscar.write('\n')
    
    #write_poscar.write('100  200' + '\n')
    write_poscar.write('\n')
    write_poscar.write(keyword + '\n')
    
    atomdict = {}
    
    for k in range(len(atomlist)): 
        atom_index = 0
        for i in range(len(lines)):   
            line_split = lines[i].split()
            if line_split[0] == atomlist[k]:
                atom_index += 1
                write_poscar.write(line_split[1]+' '+line_split[2]+' '+line_split[3]+'\n')
        atomdict[atomlist[k]] = atom_index        
    
    write_poscar.close()
    
    write_atom = open(poscar, 'r')
    content = write_atom.read()
    
    pos = content.find(keyword)
    #print(pos)
    pos = pos - 1
    if pos != -1:
        for k in range(len(atomlist)):
            #content = content[:pos] + str(atomdict[atomlist[0]]) + ' '+ str(atomdict[atomlist[1]]) + ' ' + content[pos:] 
            content = content[:pos] + str(atomdict[atomlist[k]]) + ' ' + content[pos:]
            pos += len(str(atomdict[atomlist[k]])) + 1
    
    write_atom = open(poscar, 'w')
    write_atom.write(content)
    write_atom.close()

def mkdir(path):
    path=path.strip()
    path=path.rstrip("\\")
    isExists=os.path.exists(path)
    if not isExists:
        os.makedirs(path) 

if __name__ == '__main__':

    poscar_path = "/home/pengchao/cp2k/GlycineH2O/Glycine54H2O/SCAN_Dataset/001"
    xyz = "/home/pengchao/cp2k/GlycineH2O/Glycine54H2O/GFN1-xTB/OPES_EXP/Glycine53H2O_OH_NH3CH2COOH/ProtonCV_3"
    xyzfile = os.path.join(xyz,"xyz.dat")
    searchfile = open(xyzfile, "r")
    lines = searchfile.readlines()
    searchfile.close() 
    
    atoms = int(lines[0].split()[0])
    s_index = 0
    s_list = []
    for line in lines:
        s_index += 1
        if 'generated by VMD' in line:
            s_list.append(s_index)
    
    length = '12.028'
    keyword = 'Cartesian'
    atomlist = ['H','O','N','C']
    
    for i in range(1,len(s_list)):
    #for i in range(0,3):        
        name = str(10000+i)
        mkpath = os.path.join(poscar_path, name)
        mkdir(mkpath)
        poscar = os.path.join(mkpath, 'POSCAR') 
        get_POSCAR(lines[s_list[i]:s_list[i]+atoms], poscar, name, length, atomlist, keyword)     
    